### ISSUE TITLE
Can I specified string replaced "Type" prefix?

### ISSUE THREAD

**Issue by hjianhao** [taylorchu/generic#1]
I had tried your example, I think is a nice project. 

I test the use case that using package name started with ".", it seems that the result is <packageName>TypeXXX, for example, TypeQueue rewrite to intTypeQueue. It's a bit strange. Can I specifed the string replacing the "Type" prefix to get "intQueue"?

**Comment by taylorchu** [comment]
`Type->int TypeQueue->intQueue`. `Type` and `TypeQueue` are independent type names.

(In this case, it tries to prefix `TypeQueue` to avoid potential conflicts.)

Thanks!
