### ISSUE TITLE
Can generic specified output finame for manually preventing conflicts？

### ISSUE THREAD

**Issue by hjianhao** [taylorchu/generic#2]
If the new package starts with ".", output filename will be added "package name" prefix to prevent conflicts.

Can generic specified output filename for manually preventing conflicts？

For example, I use .IntQueue for top level identifier prefix, but the output filename  is "IntQueue_queue", looks weird.

**Comment by taylorchu** [comment]
The answer is yes. I updated the readme today. Please take a look.

If the package name starts with `.`, the word after `.` is actually the prefix. (The package name is detected and set by `go generate` to the current package name.)
