### ISSUE TITLE
Preserve documentation

### ISSUE THREAD

**Issue by DmitriyMV** [taylorchu/generic#5]
This is kinda important, because when you use typed collections you definitely need the original doc.

**Comment by taylorchu** [comment]
What do you mean by `original doc`? Thanks!

**Comment by DmitriyMV** [comment]
Ahh - sorry for the confusion, by the original docs, I mean that this:
```
type TypeValue int64
type TypeKey string

// A "thread" safe map of type TypeKey:TypeValue.
// To avoid lock bottlenecks this map is dived to several (SHARD_COUNT) map shards.
type ConcurrentMap []*ConcurrentMapShared

// A "thread" safe TypeKey to TypeValue map.
type ConcurrentMapShared struct {
	items        map[TypeKey]TypeValue
	sync.RWMutex // Read Write mutex, guards access to internal map.
}
```

become this:
```
type resultConcurrentMap []*resultConcurrentMapShared

type resultConcurrentMapShared struct {
	items map[[32]byte]mytype
	sync.RWMutex
} 
```

when used like this:
```
package main

//go:generate generic github.com/DmitriyMV/concurrent-map .result TypeKey->[32]byte TypeValue->mytype
func main() {
}
```

**Comment by taylorchu** [comment]
There is an issue if we need to rename `Type` in comments. In general, it might be correct most of the time, but it will be annoying if it isn't. This is why it is removed at this moment. I can try to add the comment this week, but a PR from you is also appreciated.

**Comment by DmitriyMV** [comment]
Yeah - I don't have a generally "good" solution either, that's why I raised an issue and didn't send a PR. 😐

**Comment by DmitriyMV** [comment]
With generics coming to Go in 1.18, I think this can be closed.
