### ISSUE TITLE
Allow trait system?

### ISSUE THREAD

**Issue by DmitriyMV** [taylorchu/generic#6]
Current implementation allows you to declare simple types like

```
type TypeValue int64
type TypeKey string

// A "thread" safe map of type TypeKey:TypeValue.
// To avoid lock bottlenecks this map is dived to several (SHARD_COUNT) map shards.
type ConcurrentMap []*ConcurrentMapShared

// A "thread" safe TypeKey to TypeValue map.
type ConcurrentMapShared struct {
    items        map[TypeKey]TypeValue
    sync.RWMutex // Read Write mutex, guards access to internal map.
}
```

which wll generate fine code. However, when you need to have set of methods on your type, this becomes nontrivial:

```
type TypeValue int64
type TypeKey string

func (t *TypeValue) GetValue() string {
    return "place_holder"
}

// A "thread" safe map of type TypeKey:TypeValue.
// To avoid lock bottlenecks this map is dived to several (SHARD_COUNT) map shards.
type ConcurrentMap []*ConcurrentMapShared

// A "thread" safe TypeKey to TypeValue map.
type ConcurrentMapShared struct {
    items        map[TypeKey]TypeValue
    sync.RWMutex // Read Write mutex, guards access to internal map.
}
```

I would like to replace `func (t *TypeValue) GetValue() string` with `mytype` implementation, but currently it just copies the original, so I'm stuck with two implementations - from `mytype` and `TypeValue` one.

Relevant code:

```
package main

type mytype int64

func (t *mytype) GetValue() string {
    return "Hello World!"
}

//go:generate generic github.com/streamrail/concurrent-map .result TypeKey->[32]byte TypeValue->mytype
func main() {
}
```

**Comment by taylorchu** [comment]
My current idea is that the template should not make use of any method from TypeValue. Because you cannot make sure that the type that you replaced to have the method. But I would like to hear more about this trait system, and what we can get out of this system.

**Comment by DmitriyMV** [comment]
On further consideration, I don't think that one actually need a set of predefined implementations. Interfaces would work too, and introducing some sort of default methods (as showed above) is overkill at this point.

The "trait system" (or actually very childish version of it) and idea behind it is to check a set of constraints during compile time. Go already does that, by checking that concrete type satisfies the required interface. Still, this is runtime polymorphism and while it's nice in one situation, it doesn't work well in another.

The main idea behind this proposition is to specify and enforce requirements during compile time while getting specific implementations for the each concrete type.

Let's cut to the code. Suppose that we want to have a slice of unique items than naive implementation would be something like this:
```go
type UniqueStrings []string

func (u *UniqueStrings) Append(item string) bool {
	for _, val := range *u {
		if item == val {
			return false
		}
	}

	*u = append(*u, item)
	return true
}
```
Then we would want to generalize it, and using `generic` we could rewrite our code like this:
```go
type Type string

type TypeUniqueSlice []Type

func (u *TypeUniqueSlice) Append(item Type) bool {
	for _, val := range *u {
		if item == val {
			return false
		}
	}

	*u = append(*u, item)
	return true
}
```
Then we can use our code with any type that supports `==` (equality operator). However, when we try to use this code with type like:
```go
type MyStructType struct {
    value int64
    data  []byte // slice doesn't support equality check
}
```
the resulting code will not compile. We could define our `Type` as an interface (and avert the need of `generic` altogether). For example like this:
```go
type Type interface {
    func CheckEqual(Type) bool
}
```

and define our unique slice like:
```go
type Type interface {
    func CheckEqual(Type) bool
}

type TypeUniqueSlice []Type

func (u *TypeUniqueSlice) Append(item Type) bool {
	for _, val := range *u {
        if item.CheckEqual(val) {
			return false
		}
	}

	*u = append(*u, item)
	return true
}
```
and our type like:
```go
type MyStructType struct {
    value int64
    data  []byte // slice doesn't support equality check
}

func (m *MyStructType) CheckEqual(t Type) bool {
    val, ok := t.(MyStructType)
    // Compare value's and data
}
```
but it forces the end user to make type assertions is his/her code to compare the slices. Also, this introduces another level of indirection in memory(1) (the interfaces are represented using the pair of pointers) and hurts performance. This also makes the slice polymorphic, which may not be desirable.
However, if we introduce the "trait" system, the `generic` could replace `Type` with concrete type and validate that it satisfies the contract. It would eliminate the need of type assertions and as bonus eliminate the (1) and (2).

The resulting type, in this case, would just replace `Type` with `MyStructType` and remove the need for `val, ok := t.(MyStructType)` assertion.

As for `interface{}` because it does satisfy any type, it behavior remains unchanged.

**Comment by taylorchu** [comment]
we can introduce interface placeholder in addition to simple type like int.
Then what you said can be implemented.
